### ISSUE TITLE
Console output is merged into a step

### ISSUE THREAD

**Issue by cknabe** [IBM-Bluemix-Docs/cli#52]
![image](https://user-images.githubusercontent.com/13582620/35204864-addf30b8-fef6-11e7-9e52-47101d4b56a6.png)

Use IBM Cloud Single-Sign-On Enter a number> 2 Softlayer API endpoint URL: [https://api.softlayer.com/mobile/v3.1]> Setting account to: 278444 OK

The above should have a new line after 'Use IBM Cloud Single-Sign-On'
It should be verified that there aren't other similar instances of this on the page.
https://console.bluemix.net/docs/cli/reference/softlayer/index.html

**Comment by plindblue** [comment]
I have made the needed updates. There was a missing codeblock

IBM Cloud infrastructure (bluemix sl) commands
https://console.bluemix.net/docs/cli/reference/softlayer/index.html#softlayer_cli
