### ISSUE TITLE
what checksum is used for file verification?

### ISSUE THREAD

**Issue by MHBauer** [IBM-Bluemix-Docs/cli#53]
I was going to submit a PR, but then I saw there were a bajillion translations.

On pages such as https://console.bluemix.net/docs/cli/reference/bluemix_cli/get_started.html#getting-started

The download has a link to a checksum. The checksum used is not described.

After some trial and error, I figured out that it is a sha1 checksum. This should be explicitly stated somewhere, preferably in the link text and link name.

Further, the response when you make a request for the checksum is returned as `Content-Type | application/json` despite being plaintext.

Follow on feature requests would be to have multiple supported checksums as well as a trusted gpg signature, but I'll settle for the link text and content-type being fixed.

As an example, see an ubuntu release page such as http://mirror.pnl.gov/releases/artful/
1. it is clear what checksums are available
2. the checksum files are in standard `sum` format which contain both the checksum and filename
3. there is a signature for the checksum file that can be verified by gpg

**Comment by plindblue** [comment]
I spoke with Bo and he says that we will call out this as a sha1 sum. https://github.ibm.com/Bluemix/bluemix-cli-repo/issues/841 has been opened to address this.

**Comment by plindblue** [comment]
This has been changed from checksum to sha1sums and is now showing in production. 

IBM Cloud CLI Installer all versions
https://console.bluemix.net/docs/cli/reference/bluemix_cli/all_versions.html

Getting started with IBM Cloud CLI
https://console.bluemix.net/docs/cli/reference/bluemix_cli/get_started.html#getting-started
