### ISSUE TITLE
Release notes and compatibility asks

### ISSUE THREAD

**Issue by ert78gb** [IBM-Bluemix-Docs/cli#55]
Hi guys,

thx for the cli, but could you provide a release notes and don't do BREAKING CHANGES instantly.
I mean mark command as deprecated before you remove it or need to add extra parameter to get the same functionality.

example:
1. bx login -a ${BLUEMIX_ENDPOINT} -o ${org} -s ${cfSpace} -u "$BLUEMIX_USER" -p "$BLUEMIX_PASSWORD" --no-iam
2. bx cf push -f manifest.yml 

worked fine until today but know I have to add an extra command after the 1 step
`bx target --cf -o ${org} -s ${cfSpace}`

We have many deploy script and annoying the unplanned changes of it. :(

**Comment by plindblue** [comment]
There are currently release notes for each CLI version that you can access from the download page

IBM Cloud CLI Installer all versions
https://console-regional.ng.bluemix.net/docs/cli/reference/bluemix_cli/all_versions.html#ibm-cloud-cli-installer-all-versions

When clicking on the CLI version you will be taken to the list of complete CLI updates for each version

Releases · IBM-Cloud/ibm-cloud-cli-release
https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases

**Comment by ert78gb** [comment]
Thx the fast response, but I far as I can see it contains only high level topics. Nothing about breaking changes, not linked the relevant commits or other useful links to details. :(
