### ISSUE TITLE
Add a -q or --quiet option to the bluemix cf command

### ISSUE THREAD

**Issue by drichards-levtech** [IBM-Bluemix-Docs/cli#6]
Currently when running the Bluemix CLI for `cf `commands the CLI always displays `Invoking 'cf <command>' ...`  before invoking the actual Cloud Foundry command. For example
```
# bx cf apps
Invoking 'cf aps' ...

Getting apps in org

```

I would like to have an option that would squelch this behavior by passing a `-q` to the command. For example
```
# bx -q cf apps
Getting apps in org

```
The business case for this is when using the `bx cf ssh` command to grab something from the runtime as in https://github.com/ibmjstart/bluemix-letsencrypt where they `cat` the contents of the certs into a local file.

**Comment by boyang9527** [comment]
moved to bluemix cli repo, planned for next release
https://github.ibm.com/Bluemix/bluemix-cli/issues/504

**Comment by dolph** [comment]
The internal github issue shows as dev complete on July 28 and is now closed. I'm assuming this can be closed too, but the latest release of the bluemix CLI was much older (July 3), so I'm assuming the fix for this has not shipped.

**Comment by sefuhrer** [comment]
-q was added.
