### ISSUE TITLE
Download for verions 0.6.7 - Linux64 is not working

### ISSUE THREAD

**Issue by RayStoner** [IBM-Bluemix-Docs/cli#61]
Download is returning = Unknown version : 0.6.7

**Comment by plindblue** [comment]
Thanks for pointing this out. This is being seen for other platforms as well. I have notified the CLI developer to fix this.

**Comment by plindblue** [comment]
There was some regression with CLI version 0.6.7. This is being tested further and once corrected then the download links will be restored.
