### ISSUE TITLE
script still points to "C:\Program Files"\IBM\Bluemix\bin\bx.exe"

### ISSUE THREAD

**Issue by lee-zhg** [IBM-Bluemix-Docs/cli#67]
We are working on a hackathon preparation and use the link below to install IBM Cloud CLI
   https://console.bluemix.net/docs/cli/idt/setting_up_idt.html
which is linked to this Git project.

It does not work for Windows installation.

It appears that the script at
   https://raw.githubusercontent.com/IBM-Bluemix/developer-tools-installer/master/windows-installer/idt-win-installer.ps1
still points to "C:\Program Files"\IBM\Bluemix\bin\bx.exe". I believe the new installation folder is "C:\Program Files\IBM\Cloud" now. So, there are many failure while running the script.

If this is the issue, could someone fixes the script at the link below? Appreciate for a quick response.
    https://raw.githubusercontent.com/IBM-Bluemix/developer-tools-installer/master/windows-installer/idt-win-installer.ps1

Thanks
Lee

**Comment by lee-zhg** [comment]
There are two categories of failures. 1) kubernetes related, 2) IBM Cloud CLI related

Below are full logs for failures on Windows 10:


PS C:\WINDOWS\system32> Set-ExecutionPolicy Unrestricted; iex(New-Object Net.WebClient).DownloadString('http://ibm.biz/i
dt-win-installer')

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
[main] --==[ IBM Cloud Developer Tools - Installer for Windows, v1.2.0 ]==--
[install] Starting Installation/Update...
[install_deps] Checking for external dependency: git
[install_deps] Installing/updating external dependency: git
[install_deps] Install/update completed for: git
[install_deps] Checking for external dependency: docker
[install_deps] Installing/updating external dependency: docker
[install_deps] Install/update completed for: docker
[install_deps] Checking for external dependency: kubectl
[install_deps] Installing/updating external dependency: kubectl


    Directory: C:\Program Files


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         7/2/2018  10:55 AM                kubectl
[add_to_path] Adding C:\Program Files\kubectl to PATH
[install_deps] Install/update completed for: kubectl



[install_deps] Checking for external dependency: helm
[install_deps] Installing/updating external dependency: helm
You cannot call a method on a null-valued expression.
At line:193 char:5
+     $helm_url = ((Invoke-WebRequest https://github.com/kubernetes/hel ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

[install_deps] Helm URL :
You cannot call a method on a null-valued expression.
At line:195 char:5
+     $helm_file = $helm_url.Split("/")[-1]
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

[install_deps] Helm File:
Invoke-WebRequest : Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument
that is not null or empty, and then try the command again.
At line:197 char:23
+     Invoke-WebRequest $helm_url -UseBasicParsing -outfile "$helm_file ...
+                       ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-WebRequest], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

d-----         7/2/2018  10:55 AM                helm
Expand-7Zip : Cannot validate argument on parameter 'ArchiveFileName'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At line:202 char:17
+     Expand-7Zip $helm_file .
+                 ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Expand-7Zip], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,SevenZip4PowerShell.Expand7Zip

You cannot call a method on a null-valued expression.
At line:203 char:5
+     $tar_file = $helm_file.Replace('.gz','')
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Expand-7Zip : Cannot validate argument on parameter 'ArchiveFileName'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At line:204 char:17
+     Expand-7Zip $tar_file "C:\Program Files\helm"
+                 ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Expand-7Zip], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,SevenZip4PowerShell.Expand7Zip

Remove-Item : Cannot bind argument to parameter 'Path' because it is null.
At line:205 char:17
+     Remove-Item $helm_file -erroraction 'silentlycontinue'
+                 ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-Item], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.RemoveItemC
   ommand

Remove-Item : Cannot bind argument to parameter 'Path' because it is null.
At line:206 char:17
+     Remove-Item $tar_file  -erroraction 'silentlycontinue'
+                 ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-Item], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.RemoveItemC
   ommand

[add_to_path] Adding C:\Program Files\helm\windows-amd64 to PATH
[install_deps] Install/update completed for: helm




[install_bx] Installing IBM Cloud 'bx' CLI for Windows...
[install_bx] Downloading and installing IBM Cloud 'bx' CLI from: https://clis.ng.bluemix.net/install/powershell
Current platform is Win64. Downloading corresponding Bluemix CLI...
Download complete. Executing installer...
Install complete. Please restart to make the modification effective.
[install_bx] IBM Cloud CLI version:
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:241 char:3
+   C:\"Program Files"\IBM\Bluemix\bin\bx.exe --version
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Installing/updating IBM Cloud CLI plugins used by IDT...
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:253 char:17
+   $pluginlist = C:\"Program Files"\IBM\Bluemix\bin\bx.exe plugin list
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Checking status of plugin: Cloud-Functions
[install_plugins] Installing plugin 'Cloud-Functions'
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:261 char:9
+         C:\"Program Files"\IBM\Bluemix\bin\bx.exe plugin install -r $ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Checking status of plugin: container-registry
[install_plugins] Installing plugin 'container-registry'
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:261 char:9
+         C:\"Program Files"\IBM\Bluemix\bin\bx.exe plugin install -r $ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Checking status of plugin: container-service
[install_plugins] Installing plugin 'container-service'
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:261 char:9
+         C:\"Program Files"\IBM\Bluemix\bin\bx.exe plugin install -r $ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Checking status of plugin: dev
[install_plugins] Installing plugin 'dev'
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:261 char:9
+         C:\"Program Files"\IBM\Bluemix\bin\bx.exe plugin install -r $ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Checking status of plugin: sdk-gen
[install_plugins] Installing plugin 'sdk-gen'
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:261 char:9
+         C:\"Program Files"\IBM\Bluemix\bin\bx.exe plugin install -r $ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Running 'bx plugin list'...
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:265 char:3
+   C:\"Program Files"\IBM\Bluemix\bin\bx.exe plugin list
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Finished installing/updating plugins
Creating 'idt' script to act as shortcut to 'bx dev' command...
Out-File : Could not find a part of the path 'C:\Program Files\IBM\Bluemix\bin\idt.bat'.
At line:299 char:29
+ ... idt_batch | Out-File -Encoding ascii "C:\Program Files\IBM\Bluemix\bi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

[install] Install finished.
[quit] --==[ Finished. Total time: 00:23:31 seconds ]==--

A system restart is required. Would you like to restart now (y/N)?:

**Comment by lee-zhg** [comment]
Below is revised idt-win-installer.ps1 file that I am using as a workaround:

#------------------------------------------------------------------------------
# Script:  idt-win-installer
#------------------------------------------------------------------------------
# IBM Cloud Developer Tools - CLI installer script for Windows 10 systems
#------------------------------------------------------------------------------
# Copyright (c) 2018, International Business Machines. All Rights Reserved.
#------------------------------------------------------------------------------
$Global:VERSION="1.2.0"
$Global:PROG="IBM Cloud Developer Tools - Installer for Windows"

$Global:INSTALLER_URL="https://ibm.biz/idt-win-installer"
$Global:GIT_URL="https://github.com/IBM-Cloud/ibm-cloud-developer-tools"
$Global:SLACK_URL="https://slack-invite-ibm-cloud-tech.mybluemix.net/"
$Global:IDT_INSTALL_BMX_URL="https://clis.ng.bluemix.net/install"
$Global:IDT_INSTALL_BMX_REPO_NAME="Bluemix"
$Global:IDT_INSTALL_BMX_REPO_URL="https://plugins.ng.bluemix.net"

$Global:FORCE = $false
$Global:NEEDS_REBOOT = $false
$Global:SECS = 0

#------------------------------------------------------------------------------
function help {
  Write-Output @"

  $Global:PROG
  Usage: idt-win-installer [<args>]

  Where <args> is:
    install | update   [Default] Perform install (or update) of all needed CLIs and Plugins
    uninstall          Uninstall full IBM Cloud CLI env, including 'bx', and plugins
    help               Show this help
    --force | -f       Force updates of dependencies and other settings during update
    --trace            Eanble verbose tracing of all activity

  If "install", "update", or no action, a full CLI installation (or update) will occur:
  1. Pre-req check for 'git', 'docker', 'kubectl', and 'helm'
  2. Install latest IBM Cloud 'bx' CLI
  3. Install all required plugins
  4. Defines 'idt' shortcut to improve useability.
      - idt           : Shortcut for normal "bx dev" command
      - idt update    : Runs this installer checking for and installing any updates
      - idt uninstall : Uninstalls IDT, 'bx' cli, and all plugins  

  Chat with us on Slack: $Global:SLACK_URL, channel #developer-tools
  Submit any issues to : $Global:GIT_URL/issues

"@
}


#------------------------------------------------------------------------------
function log() {
  Write-Host "[$((Get-PSCallStack)[1].Command)] " -foreground cyan  -nonewline
  Write-Host $args
}

function warn() {
  Write-Host "[$((Get-PSCallStack)[1].Command)] " -foreground cyan  -nonewline
  Write-Host "WARN" -foreground yellow  -nonewline
  Write-Host ": $args"
}

function error() {
  Write-Host "[$((Get-PSCallStack)[1].Command)] " -foreground cyan  -nonewline
  Write-Host "ERROR" -foreground red  -nonewline
  Write-Host ": $args"
  quit
}

#------------------------------------------------------------------------------
function quit() {
  $Global:SECS = (Get-Date)-$Global:SECS
  log "--==[ Finished. Total time: $($Global:SECS.ToString("hh\:mm\:ss")) seconds ]==--"
  Write-Host ""

  #-- Request Restart to save changes to PATH.
  if ( $Global:NEEDS_REBOOT ) {
    $restart = Read-Host -Prompt "A system restart is required. Would you like to restart now (y/N)?"
    if($restart -match "[Yy]" ) {
      Restart-Computer
    } else {
      Write-Host "Note: Reboot still needed to load env variables."
    }
  } else {
    # If running in the console, wait for input before closing.
    if ($Host.Name -eq "ConsoleHost") { 
      Write-Host "Press any key to continue..."
      $Host.UI.RawUI.FlushInputBuffer()   # Make sure buffered input doesn't "press a key" and skip the ReadKey().
      $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyUp") > $null
      
      #-- turn opff trace
      Set-PSDebug -Trace 0
    }
  }
}

#------------------------------------------------------------------------------
function uninstall() {
  warn "Starting Uninstall..."
  Write-Output ""
  $reply = Read-Host -Prompt "Are you sure you want to remove IDT and IBM Cloud CLI (y/N)?"
  Write-Output ""
  if($reply -match "[Yy]") {
    log "Uninstalling IDT..."
    log "Deleting: C:\Program Files\IBM\Cloud"
    Remove-Item -Recurse -Force "C:\Program Files\IBM\Cloud" -erroraction 'silentlycontinue' 
    log "Deleting: ~/.bluemix"
    Remove-Item -Recurse -Force ~/.bluemix -erroraction 'silentlycontinue' 
    log "Uninstall complete."
  } else {
    log "Uninstall cancelled at user request"
  }
}

#------------------------------------------------------------------------------
function install() {
  log "Starting Installation/Update..."

  #-- Check if internal IBM setup
  if( get-command bx -erroraction 'silentlycontinue' ) {
    $pluginlist = C:\"Program Files"\IBM\Cloud\bin\bx.exe plugin list
    if($pluginlist -match "\bstage\b") {
      Write-Output
      $reply = Read-Host -Prompt "Use IBM internal repos for install/updates (Y/n)?"
      Write-Output
      if($reply -match "[Yy]*") {
        $Global:IDT_INSTALL_BMX_URL="https://clis.stage1.ng.bluemix.net/install"
        $Global:IDT_INSTALL_BMX_REPO_NAME="stage1"
        $Global:IDT_INSTALL_BMX_REPO_URL="https://plugins.stage1.ng.bluemix.net"
      }
    }
  }

  install_deps
  install_bx
  install_plugins
  env_setup add

  log "Install finished."

}


#------------------------------------------------------------------------------
#-- Install dependencies - git, docker, kubectl, helm.
function install_deps() {

  [Net.ServicePointManager]::SecurityProtocol = "Tls12, Tls11, Tls, Ssl3"

  #-- git
  log "Checking for external dependency: git"
  if( -not (get-command git -erroraction 'silentlycontinue') -or $Global:FORCE) {
    
    log "Installing/updating external dependency: git"
    $gitVersion = (Invoke-WebRequest "https://git-scm.com/downloads/latest" -UseBasicParsing).Content
    Invoke-WebRequest "https://github.com/git-for-windows/git/releases/download/v$gitVersion.windows.1/Git-$gitVersion-64-bit.exe" -UseBasicParsing -outfile "git-installer.exe"
    .\git-installer.exe /SILENT /PathOption="Cmd" | Out-Null
    Remove-Item "git-installer.exe"
    $Global:NEEDS_REBOOT = $true
    log "Install/update completed for: git"
  }

  #-- docker
  log "Checking for external dependency: docker"
  if( -not(get-command docker -erroraction 'silentlycontinue') -or $Global:FORCE) {
    log "Installing/updating external dependency: docker"
    Invoke-WebRequest "https://download.docker.com/win/stable/InstallDocker.msi" -UseBasicParsing -outfile "InstallDocker.msi"
    msiexec /i InstallDocker.msi /passive | Out-Null
    $Global:NEEDS_REBOOT = $true
    log "Install/update completed for: docker"
  }

  #-- kubectl
  log "Checking for external dependency: kubectl"
  if( -not( get-command kubectl -erroraction 'silentlycontinue') -or $Global:FORCE) {
    log "Installing/updating external dependency: kubectl"
    $kube_version = (Invoke-WebRequest "https://storage.googleapis.com/kubernetes-release/release/stable.txt" -UseBasicParsing).Content
    $kube_version = $kube_version -replace "`n|`r"
    Invoke-WebRequest "https://storage.googleapis.com/kubernetes-release/release/$kube_version/bin/windows/amd64/kubectl.exe" -UseBasicParsing -outfile "kubectl.exe"
    mkdir "C:\Program Files\kubectl" -erroraction 'silentlycontinue'
    Move-Item -Path "kubectl.exe" -Destination "C:\Program Files\kubectl" -force
    add_to_path("C:\Program Files\kubectl")
    $Global:NEEDS_REBOOT = $true
    log "Install/update completed for: kubectl"
  }

  #-- helm
  log "Checking for external dependency: helm"
  if( -not (get-command helm -erroraction 'silentlycontinue') -or $Global:FORCE) {
    log "Installing/updating external dependency: helm"
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    $helm_url = ((Invoke-WebRequest 'https://github.com/kubernetes/helm/releases/tag/v2.9.1' -UseBasicParsing).Links.OuterHTML | Where-Object{$_ -match 'windows-amd64.zip'} | Select-Object -first 1).Split('"')[1]
    log "Helm URL : $helm_url"
    $helm_file = $helm_url.Split("/")[-1]
    log "Helm File: $helm_file"
    Invoke-WebRequest $helm_url -UseBasicParsing -outfile "$helm_file"
    mkdir "C:\Program Files\helm" -ErrorAction SilentlyContinue
    if (-not (Get-Command Expand-7Zip -ErrorAction Ignore)) {
        Install-Package -Scope CurrentUser -Force 7Zip4PowerShell > $null
    }
    Expand-7Zip $helm_file .
    $tar_file = $helm_file.Replace('.gz','')
    Expand-7Zip $tar_file "C:\Program Files\helm"
    Remove-Item $helm_file -erroraction 'silentlycontinue'
    Remove-Item $tar_file  -erroraction 'silentlycontinue'
    add_to_path("C:\Program Files\helm\windows-amd64")
    $Global:NEEDS_REBOOT = $true
    log "Install/update completed for: helm"
  }
}

#------------------------------------------------------------------------------
#-- Add a dir to the system path
function add_to_path {
  Param($path)
  # Directly edit the registery to add kubectl to PATH. Will require a restart to stick.
  $regPath = "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment"
  $value = (Get-ItemProperty $regPath -Name Path).Path
  if ( -not ($value -match [Regex]::Escape("$path") )) {
    log "Adding $path to PATH"
    $newValue = "$value;$path"
    Set-ItemProperty -Path $regPath -Name Path -Value $newValue | Out-Null
  }  
}

#------------------------------------------------------------------------------
#-- Install Bluemix CLI.
function install_bx() {
  if( get-command bx -erroraction 'silentlycontinue') {
      Write-Output "bx already installed"
      bx update
  } else {
    log "Installing IBM Cloud 'bx' CLI for Windows..."
    $url = $Global:IDT_INSTALL_BMX_URL + "/powershell"
    log "Downloading and installing IBM Cloud 'bx' CLI from: $url" 
    Invoke-Expression(New-Object Net.WebClient).DownloadString( $url )
    $Global:NEEDS_REBOOT = $true
  }
  log "IBM Cloud CLI version:"
  C:\"Program Files"\IBM\Cloud\bin\bx.exe --version
}

#------------------------------------------------------------------------------
#-- Install Bluemix CLI Plugins.
function install_plugins {
  log "Installing/updating IBM Cloud CLI plugins used by IDT..."
  $plugins = "Cloud-Functions",
             "container-registry",
             "container-service",
             "dev",
             "sdk-gen"
  $pluginlist = C:\"Program Files"\IBM\Cloud\bin\bx.exe plugin list
  Foreach ($plugin in $plugins) {
    log "Checking status of plugin: $plugin"
    if($pluginlist -match "\b$plugin\b") {
        log "Updating plugin '$plugin'"
        C:\"Program Files"\IBM\Cloud\bin\bx.exe plugin update -r $Global:IDT_INSTALL_BMX_REPO_NAME $plugin
    } else {
        log "Installing plugin '$plugin'"
        C:\"Program Files"\IBM\Cloud\bin\bx.exe plugin install -r $Global:IDT_INSTALL_BMX_REPO_NAME $plugin
    }
  }
  log "Running 'bx plugin list'..."
  C:\"Program Files"\IBM\Cloud\bin\bx.exe plugin list
  log "Finished installing/updating plugins"
}

#------------------------------------------------------------------------------
#-- Create "idt" script to act as shortcut to "bx dev"
function env_setup() {
  Write-Output "Creating 'idt' script to act as shortcut to 'bx dev' command..."
  $idt_batch = @"
@ECHO OFF
REM #-----------------------------------------------------------
REM # IBM Cloud Developer Tools (IDT), version 1.2.0
REM # Wrapper for the 'bx dev' command, and external helpers.
REM #-----------------------------------------------------------
REM # Syntax:
REM #   idt                               - Run 'bx dev <args>'
REM #   idt update    [--trace] [--force] - Update IDT and deps
REM #   idt uninstall [--trace]           - Uninstall IDT
REM #-----------------------------------------------------------
set "action="
if "%1"=="update"    set action="update"
if "%1"=="uninstall" set action="uninstall"
if defined action (
  echo IDT launcher action: %action%
  set ifile="%temp%\idt-win-installer.ps1"
  echo Fetching latest installer to: %ifile%
  Powershell -NoProfile -ExecutionPolicy Unrestricted -Command "Invoke-WebRequest 'http://ibm.biz/idt-win-installer' -UseBasicParsing -outfile '%ifile%'"
  echo Calling: %ifile% %*
  PowerShell -NoProfile -ExecutionPolicy Unrestricted -Command "& {Start-Process PowerShell -ArgumentList '-NoProfile -ExecutionPolicy Unrestricted -File %ifile% %*' -Verb RunAs}"
) else (
  bx dev %*
)
REM #-----------------------------------------------------------
"@
  Write-Output $idt_batch | Out-File -Encoding ascii "C:\Program Files\IBM\Cloud\bin\idt.bat"
}

#------------------------------------------------------------------------------
# MAIN
#------------------------------------------------------------------------------
function main {
  log "--==[ $Global:PROG, v$Global:VERSION ]==--"
  $Global:SECS = (Get-Date)

  #-- Check for Windows 10
  if ([System.Environment]::OSVersion.Version.Major -lt 10) {
    error "This installer requires Windows 10 or higher."
  }

  #-- Check for 64-bit Platform - Dev and Helm do not have 32-bit versions.
  if ([Environment]::Is64BitProcess -ne [Environment]::Is64BitOperatingSystem) {
    error "This installer requires 64-bit Windows."
  }

  If(-NOT ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(`
    [Security.Principal.WindowsBuiltInRole] "Administrator")) {
      error "This script must be run as Administrator. Re-run this script as an Administrator!"
  }

  #-- Running as admin defaults to system32 change to home directory.
  Set-Location ~

  $ACTION="install"

  #-- Parse args
  foreach ($arg in $args) {
    switch -exact ($arg) {
      "--trace" {
        warn "Enabling verbose tracing of all activity"
        Set-PSDebug -Trace 1
      }
      "--force" {
        $Global:FORCE=$true
        warn "Forcing updates for all dependencies and other settings"
      }
      "update"    { $ACTION = "install" }
      "install"   { $ACTION = "install" }
      "uninstall" { $ACTION = "uninstall" }
      "help"      { $ACTION = "help" }
      default     { warn "Undefined Arg: $arg" }
    }
  }
  switch -exact ($ACTION) {
    "install"   { install }
    "uninstall" { uninstall }
    default     { help }
  }

  quit
}

#------------------------------------------------------------------------------
#-- Kick things off
#------------------------------------------------------------------------------
main $args

#------------------------------------------------------------------------------
# EOF
#------------------------------------------------------------------------------

**Comment by lee-zhg** [comment]
The same problems were also reported as issue #54 of IBM-Cloud/ibm-cloud-developer-tools Git repository

**Comment by plindblue** [comment]
I have contacted Bo with CLI development to review this issue further.

**Comment by triceam** [comment]
This is already fixed, and was merged into master on July 5th.
