### ISSUE TITLE
Failed steps during Helm File extraction

### ISSUE THREAD

**Issue by sandeepsharip** [IBM-Bluemix-Docs/cli#71]
Expand-7Zip : The execution has failed due to the bug in the SevenZipSharp.
Please report about it to http://sevenzipsharp.codeplex.com/WorkItem/List.aspx, post the release number and attach the
archive.
At line:206 char:5
+     Expand-7Zip $helm_file .
+     ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (SevenZip4PowerS...ip+ExpandWorker:ExpandWorker) [Expand-7Zip], SevenZipEx
   ception
    + FullyQualifiedErrorId : err01,SevenZip4PowerShell.Expand7Zip

[install_deps] Helm File: helm-v2.10.0-rc.1-windows-amd64.tar.gz
Expand-7Zip : Could not extract files! Message: File is corrupted. Data error has occured.
At line:208 char:5
+     Expand-7Zip $tar_file "C:\Program Files\helm"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (SevenZip4PowerS...ip+ExpandWorker:ExpandWorker) [Expand-7Zip], Extraction
   FailedException
    + FullyQualifiedErrorId : err01,SevenZip4PowerShell.Expand7Zip

**Comment by steveclay** [comment]
@sandeepsharip the error indicates the `helm` zip file downloaded was corrupt.  This seems to be the most likely answer as the command used in the IDT installer to unzip has not changed.  Has this been a persistent problem for you since the occurrence above?
