### ISSUE TITLE
A typo in reference/bluemix_cli/index.md

### ISSUE THREAD

**Issue by guyskk** [IBM-Bluemix-Docs/cli#8]
https://github.com/IBM-Bluemix-Docs/cli/blob/master/reference/bluemix_cli/index.md

### Online installation

With access to an internet connection, copy and paste the following command into a terminal console and execute it.

**macOS**
```
sh <(curl -fsSL https://clis.ng.bluemix.net/install/linux)    <--- osx?
```

**Linux**
```
sh <(curl -fsSL https://clis.ng.bluemix.net/install/osx)    <--- linux?
```

**Comment by mekaufman** [comment]
I have fixed this
