### ISSUE TITLE
ibmcloud account org-users has no output parameter

### ISSUE THREAD

**Issue by whitfiea** [IBM-Bluemix-Docs/cli#85]
The documentation [here](https://cloud.ibm.com/docs/cli/reference/ibmcloud?topic=cloud-cli-ibmcloud_commands_account#ibmcloud_account_org_users) for the account org-users shows it has an `--output` parameter but using the ibmcloud cli version:
```
ibmcloud --version
ibmcloud version 0.14.0+3303164-2019-02-07T02:13:34+00:00
```
it fails (and also has a `region` value that is not in the doc :
```
ibmcloud account org-users iotp-simulator --output json
FAILED
Incorrect Usage: unknown flag: --output

NAME:
  org-users - Display users in specified organization by role

USAGE:
   ibmcloud account org-users ORG [-r, --region REGION] [-a, --all]

OPTIONS:
   -a, --all                 List all users in the specified org
   -r value, --region value  Region name. Default to current region if not specified.
```

**Comment by boyang9527** [comment]
this is a doc issue. will remove it from doc.

**Comment by jpkessle** [comment]
@boyang9527 - Thanks for the PR! I reviewed the updates, and have promoted them to prod. Closing issue.
