### ISSUE TITLE
add caveat SLCLI API keys cannot be used with IBM CLI

### ISSUE THREAD

**Issue by lyndell** [IBM-Bluemix-Docs/cli#86]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
Documentation doesn't state: SLCLI API keys cannot be used with IBM CLI.  

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/cli/reference/ibmcloud?topic=cloud-cli-ibmcloud_commands_iam#ibmcloud_iam_api_key_create

3. Do you have a suggestion about how to resolve the issue?
Customer suggesting note, SLCLI API keys cannot be used with IBM CLI.  Provided text:

>  Please be aware, using the IBM Cloud CLI login with an API Key will not work with the legacy SL API Key found on control.softlayer.com. An upgraded IBM Cloud Account where Infrastructure is managed through cloud.ibm.com is required for the IBM Cloud CLI login with an API Key

**Comment by jpkessle** [comment]
@lyndell - I have added a note in this section as requested. It should be available in prod within 20 min or so. Thank you for the feedback!
