### ISSUE TITLE
IBM Cloud CLI is not shown in the 1st page of search result `cli`

### ISSUE THREAD

**Issue by archerzz** [IBM-Bluemix-Docs/cli#87]
1. What are the details of the issue you're experiencing?

If I input `cli` as key word for searching, the 1st page of search results **do not** include `IBM Cloud CLI`.

Beside, you can see duplicated entries in the search results, like `Auto-Scaling CLI`.

2. Is this issue in reference to a specific page? If so, please provide a link.

https://cloud.ibm.com/docs/search/cli

3. Do you have a suggestion about how to resolve the issue?

I think we should improve the SEO(Search Engine Optimization) here. `IBM Cloud CLI` should appear in the 1st page of search results of `cli`.

**Comment by jpkessle** [comment]
I manually checked the keywords in every /doc/cli topic this morning, and added "cli" where missing. Changes have been promoted to prod and will be available soon ;) Should the problem persist, I will check with the search engine devs to see how we can ensure this topic gets pushed higher up in the results.
