### ISSUE TITLE
Samples for ibmcloud resource search not compatible with Windows

### ISSUE THREAD

**Issue by uniack** [IBM-Bluemix-Docs/cli#90]
Most of the samples given for the "ibmcloud resource search" CLI command do not work on MS Windows unless the single quotes are changed to double quotes.  The command returns "FAILED Incorrect usage" unless double quotes are used.

The same samples are returned when using the CLI command as well.

https://cloud.ibm.com/docs/cli/reference/ibmcloud?topic=cloud-cli-ibmcloud_commands_resource#ibmcloud_resource_search

I did not try every sample, but I am assuming that with Windows either the Lucene syntax or ibmcloud syntax requires double quotes on Windows.

Please update the documentation for OS specific samples (or mention in the doc they need to be changed to double quotes).

Also, the same samples that are returned from the ibmcloud CLI command itself need to be OS specific.

Thanks, Steve
uniack@us.ibm.com

**Comment by jpkessle** [comment]
@boyang9527 - Hi Bo, Can you provide any insight on this issue? Is there something we need to correct on the docs ?

**Comment by damianovesperini** [comment]
@jpkessle Hi, we have in planning this issue for the next week.
I will let you know as soon as the fix are available.

Thanks, Damiano

**Comment by damianovesperini** [comment]
The fix was done. 
It will be available with the next version of IBM CLI 0.17.0
