### ISSUE TITLE
can not install IBM cloud CLI envt

### ISSUE THREAD

**Issue by bhavna-agrawal** [IBM-Bluemix-Docs/cli#91]
curl -sL https://ibm.biz/idt-installer | bash

fails on:

**Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/version: dial unix /var/run/docker.sock: connect: permission denied**

and

[install_bx] Downloading and installing IBM Cloud 'bx' CLI from: https://clis.ng.bluemix.net/install/linux
Current platform is linux64. Downloading corresponding IBM Cloud CLI...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   120    0   120    0     0     94      0 --:--:--  0:00:01 --:--:--    94
  0     0    0     0    0     0      0      0 --:--:--  0:02:11 --:--:--     0
**curl: (7) Failed to connect to public.dhe.ibm.com port 443: Connection timed out
Download failed. Please check your network connection. Quit installation.**

**Comment by jpkessle** [comment]
@bhavna-agrawal - These messages look like a firewall or internet connection issue not being able to access the installer script. For example, you should be able to access the script in a browser directly with https://ibm.biz/idt-installer. If you can't then you are being blocked on your end.

Are you still experiencing issues? Can you run the `curl -sL https://ibm.biz/idt-installer | bash` command from a different client network with less restrictions?

**Comment by bhavna-agrawal** [comment]
adding a line to /etc/hosts worked:
170.225.15.112  public.dhe.ibm.com
